services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/auth-db
    depends_on:
      - mongo

  event:
    build:
      context: .
      dockerfile: apps/event/Dockerfile
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://mongo:27017/event-db
    depends_on:
      - mongo

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    depends_on:
      - auth
      - event

volumes:
  mongo-data:
